### ISSUE TITLE
An example for O2PLS

### ISSUE THREAD

**Issue by shu-hai** [selbouhaddani/OmicsPLS#1]
Hi, selbouhaddani,
Could you please provide an example to implement the O2PLS? 
For example, what is the difference between the two cross-validation functions, i.e., crossval_o2m_adjR2() and crossval_o2m()?
How to obtain the resulting common and distinctive matrices for each block?
When I open the OmicsPLS_vignette.Rmd in Firefox browser, the math formula are not recognizable.

Thanks.

**Comment by selbouhaddani** [comment]
Thanks for your interest in the OmicsPLS package! 
I have uploaded a vignette (OmicsPLS_vignette.pdf), it contains a walkthrough for a freely available dataset. I hope you will find it useful. A shorter built-in vignette is also available with the `vignette("OmicsPLS_vignette")` command.
 
Some remarks:
- Note that you don’t need to download the data manually, running the code does this for you.
- If you don’t want to minimize prediction error, a “scree-plot” can be more useful to determine the number of components; as a heuristic _n+nx_ can be determined by plotting `svd(X)$d^2`, for _n+ny_ plot `svd(Y)$d^2` and for _n_ plot `svd(crossprod(X,Y))$d^2`.
- The code for producing plots is included, have a look at the packages that need to be installed. 
- The extra input parameters to plot are handled by `geom_text()` (so you can look at that help page for info and more input options). Some manipulation is needed if you want geom_point instead (basically set the `geom_text` transparency to 1, see longer vignette). 
- Finally see the help pages of `?o2m` to retrieve model estimates.

As always, if you have difficulties I am happy to try to help. 
If you come across suggestions/bugs/ambiguities please do report them (via mail or file an issue on github). 
 
Best wishes,
Said
