### ISSUE TITLE
Residuals are not populated when using NIPALS

### ISSUE THREAD

**Issue by krassowski** [selbouhaddani/OmicsPLS#11]
`E` and `Ff` are set to zero in `o2m2` and are not changed afterwards.

https://github.com/selbouhaddani/OmicsPLS/blob/d32510a1cbc3ac98783bef009a41e6e926dbaecd/R/OmicsPLS_o2m.R#L477

Out of curiosity, is 't' in `Tt` or 'f' in `Ff` meaningful or are those just added due to potentially conflicting symbols in R or something?

**Comment by selbouhaddani** [comment]
Thanks again, will look at it later today.

The extra t is just to avoid using T and F as in `TRUE `and `FALSE`.

**Comment by krassowski** [comment]
Thank you, that makes sense to me now. It was quite confusing initially (I was suspecting that it might be a transpose of T when I first saw the Tt symbol).

**Comment by selbouhaddani** [comment]
Thanks, fixed in the current github version. Please let me know is something is still wrong
