### ISSUE TITLE
Difference in the o2m objects produced by full and stripped versions of o2m

### ISSUE THREAD

**Issue by krassowski** [selbouhaddani/OmicsPLS#13]
The objects returned by the stripped versions use `T_Yosc.`:

https://github.com/selbouhaddani/OmicsPLS/blob/69086e54f6730a33d80d7bfa759a2228112a1636/R/OmicsPLS_o2m.R#L598

https://github.com/selbouhaddani/OmicsPLS/blob/69086e54f6730a33d80d7bfa759a2228112a1636/R/OmicsPLS_o2m.R#L727

 while non-stripped versions use `T_Yosc`:

https://github.com/selbouhaddani/OmicsPLS/blob/69086e54f6730a33d80d7bfa759a2228112a1636/R/OmicsPLS_o2m.R#L202

https://github.com/selbouhaddani/OmicsPLS/blob/69086e54f6730a33d80d7bfa759a2228112a1636/R/OmicsPLS_o2m.R#L477

Is it intentional or just a typo? The documentation mentions the latter only.

**Comment by selbouhaddani** [comment]
fixed in the current version on github
