### ISSUE TITLE
Add VIP function for OmicsPLS

### ISSUE THREAD

**Issue by guokai8** [selbouhaddani/OmicsPLS#2]
Did you try to add VIP(variable influence on projection) function to calculate the VIP for the OmicsPLS?
Thanks!

**Comment by selbouhaddani** [comment]
Thank you very much for the excellent suggestion. I haven't implemented this function yet. Perhaps in a later stage it will become part of the package. Of course you are free to contribute to the package if you happen to have code you routinely use. 
Thanks for using the OmicsPLS package!

**Comment by selbouhaddani** [comment]
Editing closing reason as not planned
