### ISSUE TITLE
Scores does not work for ortogonal scores

### ISSUE THREAD

**Issue by krassowski** [selbouhaddani/OmicsPLS#8]
https://github.com/selbouhaddani/OmicsPLS/blob/c2e334820bc82b66051e48ddb35daa1643879bb2/R/OmicsPLS.R#L783

To me, it seems that the dots are the issue here (fit does not have attributes `T_Yosc.` and `U_Xosc.`, but has `T_Yosc` and `U_Xosc`)

**Comment by selbouhaddani** [comment]
Thanks krassowski, for reporting and suggesting a fix! 

I included it together with some changes in the new version 1.2.1. Unfortunately, too late to include it in the version on cran 1.2.0 (which was uploaded yesterday!)
